//------------------------------------------------------------------------
// Copyright(c) 2023 Arvin Plugin.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"arvin-guitar-amp-vst3.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"arvin-guitar-amp-vst3 VST3 (64Bit)"
#else
#define stringFileDescription	"arvin-guitar-amp-vst3 VST3"
#endif
#define stringCompanyName		"Arvin Plugin\0"
#define stringLegalCopyright	"Copyright(c) 2023 Arvin Plugin."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
